### ISSUE TITLE
App gone from Google Play?

### ISSUE THREAD

**Issue by flemesre** [file-acomplaint/hackenbush#7]
I've had Hackenbush on my old phone for a while now, greatly enjoyed it. I had to switch devices and it didn't transfer over - in fact, it seems to be fully gone from the play store. Is that intentional?

**Comment by lennart-finke** [comment]
Thank you for playing! Yes, Google automatically kicks developers out of the store if they don't publish anything for a year or so, which is also what happened here. I don't understand that policy, but I still want to find the time to get it back up if people enjoy it.

In the meantime, you can download an .apk install for an older version [here](https://github.com/lennart-finke/hackenbush/releases/download/v0.6/Hackenbush.apk).

**Comment by flemesre** [comment]
That's unfortunate. Thanks for the link - was able to install it no problem.
